### ISSUE TITLE
Sponsor Offer management

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/lifebank#187]
# As a sponsor I need to be able to set and edit offer description and rules, so I can provide clear and up-to-date information to donors.

## Tasks:
- [ ] Design views. @murillojorge #256 
- [ ] Instructive copy @ldrojas #256 
- [x] Offers management listing view CRUD. @JustinCast 
- [x] Edit view. @JustinCast 
- [x] Update DB model, Hasura, Happi. @JustinCast 

## Elements (*required):
- [x] Type*: Sponsors can select offer types: discount, gift, benefit, other
- [x] Token value*: Sponsors can redeem limited or unlimited tokens.
- [x] Expiration date*: Sponsors can redeem on a specific interval.
- [x] Active*: Sponsors can enable or disable offers.
- [x] Online*: Sponsors can create online-only offers.
- [x] Description*: Sponsors can describe their offers.
- [x] Images: Sponsors can link to multiple images.

- [x] Sponsors can delete offers.
- [x] Sponsors can create new offers.
- [x] Sponsors can set multiple offers.
- [x] Sponsors can modify the offers after launch.

## Miscellaneous

**Comment by murillojorge** [comment]
@murillojorge and @ldrojas We need to get our part done to complete this task.

**Comment by murillojorge** [comment]
Design will be handled with issue #256
