### ISSUE TITLE
Offer approval by Lifebanks

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/lifebank#331]
As a Lifebank I'd like to select which offers I want to support, so I can comply with regulations. 

- [x] Lifebanks can approve offers by checking boxes #334 
- [x] Define and apply design for lifebank users #332 
- [x] Define and apply design for donor users #333
- [x] View design for sponsors #564 
- [x]  Mobile responsiveness #616

Lifebank user tasks: #332 
Donor user tasks: #333
DB tasks: #334

### 1.  Create a new `offers` table 
     - `offer_name` (name) (pk) ( < 12 && a-z.1-5) (eg: cafegratis)
     - `sponsor_name` (name)
     - `cost` (uint)  

#### Persistant Attributes 

 - `offer_name`
 -  `sponsor_name`
 - `cost`
 
#### Additional Attributes 
-  `description` 

### 4. Create a join table called `lifebank_offers`  
    - id (int) (pk) 
    - offer_name (name)
    - community (asset) 

### Create new `redeem`  action

         - donor: - donor (name)
         - offer: - offer_id (id)

Reddem action needs to validate 

         - a lifebank_offer exists in the donors community
         - the donor has enough funds to pay to the cost set in offers table

### Modify Existing transfer action 

add a new validation so no transfers can occur from donors to sponsors (only through offers)

- from : name
- to: name
- amount: int
- memo: string

**Categories:**
- Discounts
- Free products
- Coupons
- Benefits 
- Badges

**Attributes of offers**

- Title of the offer*
- Description*
- Category (unique)*
- Beginning and expiration dates*
- Location(s) if they have branches 
- Token cost*
- Images/photos (if they don’t upload any, we can preload images from their profile)
- Details/restrictions
- Restrictions to redeem token per user(?)
- Logo of the sponsor (preloaded from profile)*
- Button to view profile*
