### ISSUE TITLE
A redeemed token is transferred to the lifebank that needs tokens the most

### ISSUE THREAD

**Issue by ldrojas** [eoscostarica/lifebank#555]
When a donor redeems a token at a business, the token will be transferred automatically to the lifebank that needs that token the most. This means that, if the lifebank is managing large sums of tokens, they will require new tokens to send to donors, thus they will receive the appropriate amount of tokens.

- [x] What the donor sees. #556
- [x] What the business sees. #557
- [x] What the lifebank sees. #558
